// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Ldq-lcLpYUAAm-R18lsgE3zhrlAQBtU',
    appId: '1:39634296184:web:b8a29f4ec3ce556d377c8d',
    messagingSenderId: '39634296184',
    projectId: 'notes-app-tiara',
    authDomain: 'notes-app-tiara.firebaseapp.com',
    storageBucket: 'notes-app-tiara.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBakPoC_6V3Z2SU1V5u59avQczL9hmhP7Q',
    appId: '1:39634296184:android:b7b7cc3a0dea0321377c8d',
    messagingSenderId: '39634296184',
    projectId: 'notes-app-tiara',
    storageBucket: 'notes-app-tiara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFj_Z2J4PdcUPnrtc3zfFA9ahWI1OiGY4',
    appId: '1:39634296184:ios:0c1e8927b89ce9b2377c8d',
    messagingSenderId: '39634296184',
    projectId: 'notes-app-tiara',
    storageBucket: 'notes-app-tiara.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFj_Z2J4PdcUPnrtc3zfFA9ahWI1OiGY4',
    appId: '1:39634296184:ios:0c1e8927b89ce9b2377c8d',
    messagingSenderId: '39634296184',
    projectId: 'notes-app-tiara',
    storageBucket: 'notes-app-tiara.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Ldq-lcLpYUAAm-R18lsgE3zhrlAQBtU',
    appId: '1:39634296184:web:21f072b5b8be77c3377c8d',
    messagingSenderId: '39634296184',
    projectId: 'notes-app-tiara',
    authDomain: 'notes-app-tiara.firebaseapp.com',
    storageBucket: 'notes-app-tiara.firebasestorage.app',
  );
}
